//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicar_Trabajo
    {
        public int id { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Aplicacion { get; set; }
        public Nullable<int> id_Trabajo { get; set; }
        public byte[] doc { get; set; }
    
        public virtual Trabajos Trabajos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
