//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajosOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrabajosOnlineEntities : DbContext
    {
        public TrabajosOnlineEntities()
            : base("name=TrabajosOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicar_Trabajo> Aplicar_Trabajo { get; set; }
        public virtual DbSet<Categoria_Trabajos> Categoria_Trabajos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trabajos> Trabajos { get; set; }
        public virtual DbSet<Trabajos_habilidades> Trabajos_habilidades { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
