//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajosOnline.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Trabajos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajos()
        {
            this.Aplicar_Trabajo = new HashSet<Aplicar_Trabajo>();
        }

        public int id { get; set; }
        public Nullable<int> id_Habilidades { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> fecha_Publicacion { get; set; }
        public string condiciones { get; set; }
        public string Estado { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string Empesa { get; set; }
        public string Beneficios { get; set; }
        public string Credenciales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplicar_Trabajo> Aplicar_Trabajo { get; set; }
        public virtual Categoria_Trabajos Categoria_Trabajos { get; set; }
        public virtual Trabajos_habilidades Trabajos_habilidades { get; set; }
    }
}
